# Generated by Django 3.1.7 on 2021-04-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
