# Generated by Django 3.1.7 on 2021-04-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
